In [1]:
import numpy as np
import pandas as pd

In [2]:
R = np.array([[5,3,0,1],[4,0,0,1],[1,1,0,5],[1,0,0,4],[0,1,5,4]])


In [3]:
R

array([[5, 3, 0, 1],
       [4, 0, 0, 1],
       [1, 1, 0, 5],
       [1, 0, 0, 4],
       [0, 1, 5, 4]])

In [27]:
R.shape

(5, 4)

In [28]:
R

array([[5, 3, 0, 1],
       [4, 0, 0, 1],
       [1, 1, 0, 5],
       [1, 0, 0, 4],
       [0, 1, 5, 4]])

In [7]:
N = len(R)
N

5

In [8]:
M = len(R[0])

In [9]:
M

4

In [10]:
K = 2

In [12]:
P = np.random.rand(N,K)
Q = np.random.rand(M,K)

In [14]:
Q

array([[ 0.80961346,  0.96419722],
       [ 0.35841679,  0.68420105],
       [ 0.15326289,  0.81545492],
       [ 0.25418394,  0.19649818]])

In [19]:
def matrix_factorization(R, P, Q, K, steps=5000, alpha=0.0002, beta=0.02):

    Q = Q.T

    for step in range(steps):

        for i in range(len(R)):

            for j in range(len(R[i])):

                if R[i][j] > 0:

                    eij = R[i][j] - np.dot(P[i,:],Q[:,j])

                    for k in range(K):

                        P[i][k] = P[i][k] + alpha * (2 * eij * Q[k][j] - beta * P[i][k])

                        Q[k][j] = Q[k][j] + alpha * (2 * eij * P[i][k] - beta * Q[k][j])

        eR = np.dot(P,Q)

        e = 0

        for i in range(len(R)):

            for j in range(len(R[i])):

                if R[i][j] > 0:

                    e = e + pow(R[i][j] - np.dot(P[i,:],Q[:,j]), 2)

                    for k in range(K):

                        e = e + (beta/2) * (pow(P[i][k],2) + pow(Q[k][j],2))

        if e < 0.001:

            break

    return P, Q.T

In [20]:
nP, nQ = matrix_factorization(R, P, Q, K)


In [25]:
nR = np.dot(nP, nQ.T)


In [26]:
nR

array([[ 4.98063194,  2.97411813,  2.72041387,  0.99975224],
       [ 3.97734253,  2.38840647,  2.39405136,  0.99693536],
       [ 1.02855517,  0.93462864,  5.86605203,  4.95879849],
       [ 0.98599734,  0.84326145,  4.75106407,  3.97211094],
       [ 1.37709703,  1.07560697,  4.94491025,  4.03290101]])